apiVersion: v1
kind: Pod
metadata:
  name: first-api-dec
  labels:
    name: myapp
    type: restapi
spec:
  containers:
  - name: simple-api
    image: docker.io/kadriayoub/learn-kube:3.1 
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 30005

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: api-server
# spec:
#   type: NodePort
#   ports:
#     - targetPort: 3000
#       port: 8081
#       nodePort: 30005
#   selector:
#     app: myapp
#     type: restapi